//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ProjectsModel", "ProjectsPerPerson", "Person", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Domain.Person), "Project", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Domain.Project))]

// Original file name:
// Generation date: 14/03/2009 16:24:16
namespace Domain
{
    
    /// <summary>
    /// There are no comments for ProjectsEntities in the schema.
    /// </summary>
    public partial class ProjectsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ProjectsEntities object using the connection string found in the 'ProjectsEntities' section of the application configuration file.
        /// </summary>
        public ProjectsEntities() : 
                base("name=ProjectsEntities", "ProjectsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ProjectsEntities object.
        /// </summary>
        public ProjectsEntities(string connectionString) : 
                base(connectionString, "ProjectsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ProjectsEntities object.
        /// </summary>
        public ProjectsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ProjectsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Person> People
        {
            get
            {
                if ((this._People == null))
                {
                    this._People = base.CreateQuery<Person>("[People]");
                }
                return this._People;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Person> _People;
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Project> Projects
        {
            get
            {
                if ((this._Projects == null))
                {
                    this._Projects = base.CreateQuery<Project>("[Projects]");
                }
                return this._Projects;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Project> _Projects;
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
    }
    /// <summary>
    /// There are no comments for ProjectsModel.Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ProjectsModel", Name="Person")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::Domain.Developer))]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::Domain.Analyst))]
    public partial class Person : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Person CreatePerson(global::System.Guid id, string firstName, string name)
        {
            Person person = new Person();
            person.Id = id;
            person.FirstName = firstName;
            person.Name = name;
            return person;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ProjectsModel", "ProjectsPerPerson", "Project")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Project> Projects
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Project>("ProjectsModel.ProjectsPerPerson", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Project>("ProjectsModel.ProjectsPerPerson", "Project", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ProjectsModel.Developer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ProjectsModel", Name="Developer")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Developer : Person
    {
        /// <summary>
        /// Create a new Developer object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Developer CreateDeveloper(global::System.Guid id, string firstName, string name)
        {
            Developer developer = new Developer();
            developer.Id = id;
            developer.FirstName = firstName;
            developer.Name = name;
            return developer;
        }
        /// <summary>
        /// There are no comments for Property PreferedLanguage in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferedLanguage
        {
            get
            {
                return this._PreferedLanguage;
            }
            set
            {
                this.OnPreferedLanguageChanging(value);
                this.ReportPropertyChanging("PreferedLanguage");
                this._PreferedLanguage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PreferedLanguage");
                this.OnPreferedLanguageChanged();
            }
        }
        private string _PreferedLanguage;
        partial void OnPreferedLanguageChanging(string value);
        partial void OnPreferedLanguageChanged();
    }
    /// <summary>
    /// There are no comments for ProjectsModel.Analyst in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ProjectsModel", Name="Analyst")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Analyst : Person
    {
        /// <summary>
        /// Create a new Analyst object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Analyst CreateAnalyst(global::System.Guid id, string firstName, string name)
        {
            Analyst analyst = new Analyst();
            analyst.Id = id;
            analyst.FirstName = firstName;
            analyst.Name = name;
            return analyst;
        }
        /// <summary>
        /// There are no comments for Property Methodology in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Methodology
        {
            get
            {
                return this._Methodology;
            }
            set
            {
                this.OnMethodologyChanging(value);
                this.ReportPropertyChanging("Methodology");
                this._Methodology = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Methodology");
                this.OnMethodologyChanged();
            }
        }
        private string _Methodology;
        partial void OnMethodologyChanging(string value);
        partial void OnMethodologyChanged();
    }
    /// <summary>
    /// There are no comments for ProjectsModel.Project in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ProjectsModel", Name="Project")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Project : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="deadline">Initial value of Deadline.</param>
        public static Project CreateProject(global::System.Guid id, string name, global::System.DateTime deadline)
        {
            Project project = new Project();
            project.Id = id;
            project.Name = name;
            project.Deadline = deadline;
            return project;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Deadline in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Deadline
        {
            get
            {
                return this._Deadline;
            }
            set
            {
                this.OnDeadlineChanging(value);
                this.ReportPropertyChanging("Deadline");
                this._Deadline = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Deadline");
                this.OnDeadlineChanged();
            }
        }
        private global::System.DateTime _Deadline;
        partial void OnDeadlineChanging(global::System.DateTime value);
        partial void OnDeadlineChanged();
        /// <summary>
        /// There are no comments for People in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ProjectsModel", "ProjectsPerPerson", "Person")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Person> People
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Person>("ProjectsModel.ProjectsPerPerson", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Person>("ProjectsModel.ProjectsPerPerson", "Person", value);
                }
            }
        }
    }
}
